---
title: "co-factors"
author: "Carolina Lobato"
date: "2023-06-02"
output: html_document
---

```{r include = FALSE}
library(phyloseq)
library(microbiome)
library(microbiomeutilities)
library(RColorBrewer)
library(ranacapa)
library(tidyverse)
```

## Import data

```{r, echo = FALSE}
# Change metadata
metadata$provider[metadata$provider == "White Label"] <- "Sensi Seeds"
metadata <- sample_data(metadata)
```

## Beta-Diversity

```{r, echo = FALSE}
#ps_new <- subset_samples(ps, !is.na(inflorescence) & chemotype2 == "Low" & domestication == c("Cross hybrid", "Inbred line")) # flower (Subset A, n=13)

#ps_new <- subset_samples(ps, !is.na(chemotype2) & inflorescence == "Dioecious" & domestication == c("Cross hybrid")) # chem (Subset B, n=8)

#ps_new <- subset_samples(ps, !is.na(domestication) & chemotype2 == "Low") # dom-hemp (Subset C, n=26)

#ps_new <- subset_samples(ps, !is.na(domestication) & chemotype2 == "High") # dom-chem-mj (Subset D, n=9)


# unique(row.names(sample_data(ps_new)))
# ps_mer <- merge_samples(ps, "cultivar")

ps_new <- subset_samples(ps, !is.na(chemotype) & provider == "Sensi Seeds")
check <- unique(ps_new@sam_data[["cultivar"]]);check

# correct uneven sequencing depth using cumulative sum scaling (CSS) instead of rarefaction
bh_css <- metagMisc::phyloseq_transform_css(ps_new, norm = TRUE, log = TRUE); bh_css
```

### PCoA

```{r, echo = FALSE}
# Non-metric MultiDimenstional Scaling
bh_MDS <- ordinate(bh_css, "MDS", "bray", trymax = 1000); bh_MDS

mycolors <- colorRampPalette(brewer.pal(6, "Paired"))(6)
column1 <- sample_data(bh_css)$domestication
column2 <- sample_data(bh_css)$chemotype
column3 <- sample_data(bh_css)$cultivar

plot_ordination(bh_css, bh_MDS) + 
  geom_point(
    aes(col = as.factor(column1), 
        shape = as.factor(column2)),
        size = 5,
    show.legend = T) +
  geom_text(aes(label = as.factor(column3)), 
            size = 2) +
#  scale_shape_manual(values = c(19, 18, 15, 17)) +
  # stat_ellipse(type = "norm", linetype = 1, level = 0.95) + 
  scale_color_manual(values = mycolors) +
  theme_classic() +
  theme(
    legend.position = "right",
    legend.box = "vertical",
    legend.direction = "vertical") +
  ggtitle("") +
  labs(color = "", shape = "")

ggsave(
  "outputs/beta-div/mds-bray-chem-dom-mj.png",
  width = 20,
  height = 18,
  units = "cm",
  scale = 1,
  dpi = 600
)
```

### Distances

```{r, echo = FALSE}
dist_matrix_t <- t(data.frame(otu_table(bh_css))) # transpose the css ASV table as a matrix
df_css <- data.frame(sample_data(bh_css)) # get data
bh_css_bray <- vegan::vegdist(dist_matrix_t, method = "bray") # generate a bray distance object

# test dispersion
dispersion <- vegan::betadisper(bh_css_bray, df_css$cultivar, bias.adjust = TRUE, sqrt.dist = TRUE)
anova(dispersion) # under the H0 = no difference in dispersion between groups
vegan::permutest(dispersion, pairwise = TRUE, permutations = 999)
plot(dispersion)
boxplot(dispersion, main = "", xlab = "")

# test significance
vegan::adonis2(bh_css_bray ~ chemotype, data = df_css)
anosim(dist_matrix_t, df_css$cultivar, permutations = 999, distance = "bray")

# transpose if necessary to test pairwise significance
if (taxa_are_rows(bh_css)) {
    bh_css <- t(bh_css)
}
# df <- psmelt(bh_css)
# css_table <- data.frame(dist_matrix_t) %>% rownames_to_column("replicates") 

metadata <-
  as(sample_data(bh_css), "data.frame") %>%
  select(replicates, cultivar)

css_table <-
  as.data.frame(otu_table(bh_css)) %>%
  rownames_to_column("replicates")

df <-
  css_table %>%
  inner_join(metadata, by = "replicates") %>%
  select(cultivar, starts_with("ASV"))
  
pwadonis <-
  pairwiseAdonis::pairwise.adonis(
  df[, 2:5860],
  as.factor(df$cultivar),
  sim.function = "vegdist",
  sim.method = "bray",
  p.adjust.m = "fdr"
) # pairwise comparisons

# coerce to data.frame and save
pwadonis_df = as.data.frame(pwadonis)
write.csv(pwadonis_df, file = "outputs/co-factors/pw-adonis.csv")
```
