---
title: "network"
output: html_document
date: "2023-10-19"
---

```{r}
library(SpiecEasi)
library(igraph)
library(GGally)
```

## Subset data

```{r}
load("outputs/r/308_rare_taxa/bh-5-01.RData")

Bacteria_seed_china <- subset_samples(bh_pruned, cultivar == "NA BG China")
Bacteria_seed_china <- prune_taxa(taxa_sums(Bacteria_seed_china) > 0, Bacteria_seed_china); Bacteria_seed_china # 532 taxa / 392 taxa

save(Bacteria_seed_china, 
     file = "outputs/r/308_rare_taxa/bac-china-pru.RData")
```

## Create Network

```{r}
load("outputs/r/308_rare_taxa/bac-china-pru.RData")

# Warning: Optimal lambda may be outside the supplied values
se.mb.china_01_10_20 <- spiec.easi(
  Bacteria_seed_china,
  method = "mb",
  sel.criterion = "bstars",
  lambda.min.ratio = 0.5, # smaller -> more edges
  nlambda = 10,
  pulsar.params = list(rep.num = 20, 
#                       ncores = 4, 
                       seed = 12345),
  verbose = T)

getStability(se.mb.china_01_10_20) 
sum(getRefit(se.mb.china_01_10_20)) / 2 
se.mb.china_01_10_20$select$stars$summary

save(se.mb.china_01_10_20, file = "outputs/r/308_rare_taxa/se-china-pru.RData")
```

```{r}
load("outputs/r/308_rare_taxa/se-china-pru.RData")

bm <- symBeta(getOptBeta(se.mb.china_01_10_20), mode = "maxabs")

betas <- Matrix::summary(t(bm))[, 3]
weights <- ( 1 - Matrix::summary(t(bm))[, 3] ) / 2
edges.attr <- list(beta = betas, weight = weights)

ig.mb.china <- SpiecEasi::adj2igraph(
  Matrix::drop0(getRefit(se.mb.china_01_10_20)),
  rmEmptyNodes = TRUE,
  edge.attr = edges.attr,
  vertex.attr = list(name = taxa_names(Bacteria_seed_china))
)

write_graph(ig.mb.china, "outputs/r/308_rare_taxa/china/cyt-china-pru-network.gml", format = "gml")
```

```{r}
# bm <- symBeta(getOptBeta(se.mb.china_01_10_20), mode = "maxabs")
otu.ids <- taxa_names(Bacteria_seed_china)
edges <- E(ig.mb.china) # spiec.graph
edge.colors <- c()
for (e.index in 1:length(edges)) {
  adj.nodes = ends(ig.mb.china, edges[e.index])
  xindex = which(otu.ids == adj.nodes[1])
  yindex = which(otu.ids == adj.nodes[2])
  beta = bm[xindex, yindex]
  if (beta > 0) {
    edge.colors = append(edge.colors, "forestgreen")
  } else if (beta < 0) {
    edge.colors = append(edge.colors, "red")
  }
}
```

```{r}
E(ig.mb.china)$color <- edge.colors

spiec.graph.b <- ig.mb.china
nodenames <- V(spiec.graph.b)$name
# V(spiec.graph.b)$name <-
#   getTaxonomy(nodenames, Bacteria_seed_china, useRownames = T)
E(spiec.graph.b)$arrow.size = 5
V(spiec.graph.b)$color = "white"
V(spiec.graph.b)$frame.color = "black"
tkplot(spiec.graph.b)
```

```{r}
as.data.frame(degree(ig.mb.china))

```
