---
title: "Microbiome Analysis"
author: "Carolina Lobato"
date: "2022-11-07"
output: html_document
---

```{r loadlib}
library(ggplot2)
library(dplyr)
require(maps)
require(viridis)
library(Rmisc)
library(rsvg)
library(ggsvg)
library(scatterpie)
```

# Cannabis lineages

```{r}

└── RV Georgia 86
   ├── Bredemann 
   │ └── Eletta Campana
   │
   ├── Finola
   │
   ├── Krasnoyarskaya
   │
   ├── Havellander
   │  └── Fibridia
   │     ├── Futura 75
   │     └── Eletta Campana
   │
   └── Schurig
      ├── Hohenthurmer G. R.
      ├── Fasamo
      │
      └── Fibrimon
         ├── Felina 32
         ├── Fedora 17
         ├── Ferimon
         ├── Santhica 27
         ├── Futura 75
         └── Beniko

└── RV Romania 94
   └── Silvana x Manitoba Poison/

└──  Carmagnola
   ├── Krasnoyarskaya
   ├── Kompolti
   │  └── Felina 32
   └── Eletta Campana

└──  Hindu Kush 
   └──  Master Kush

└── Afghani 1
   ├── The Church CBD
   └──  Skunk 1

```

## Variant Origin Map

```{r map}
map <- read.table("region", header = TRUE, sep = "\t")
head(map)
dim(map)
world_map <- map_data("world")
worldSubset <- inner_join(world_map, map, by = "region")
head(worldSubset)

## Define countries outlines as a geom_polygon layer
country.layer <- 
  geom_polygon(
    aes(x = long, y = lat, group = group),
    data = world_map,
    fill = NA,
    color = "black",
    size = 0.3
)

## Let's ditch many of the unnecessary elements
plain <- theme(
  axis.text = element_blank(),
  axis.line = element_blank(),
  axis.ticks = element_blank(),
  panel.border = element_blank(),
  panel.grid = element_blank(),
  axis.title = element_blank(),
  panel.background = element_rect(fill = "white"),
  plot.title = element_text(hjust = 0.5)
)

## Set the points coordinates
landmarks <- data.frame(
  long = c(50, 74, 8, 16, 43, 126, 25, 20),
  lat = c(60, 37, 45, 41, 43, 40, 47, 50),
  names = c(
    "Central Russia",
    "Hindu Kush",
    "North Italy",
    "South Italy",
    "Georgia",
    "North Korea",
    "Romania",
    "Slovakia"
  ),
  nsamples = c(4, 3, 1, 2, 1, 1, 1, 2),
  Hybrid = c(4, 1, 0, 0, 0, 0, 0, 1),
  Landrace = c(0, 2, 1, 0, 0, 0, 0, 0),
  Wild = c(0, 0, 0, 2, 1, 1, 1, 1),
  stringsAsFactors = FALSE
)
svg_url <- 'https://www.svgrepo.com/download/202874/cannabis-drug.svg'
svg_txt <- paste(readLines(svg_url), collapse = "\n")
grid::grid.draw(svg_to_rasterGrob(svg_txt))

## Map
Fig1_map <-
  ggplot() +
  geom_polygon(
    data = worldSubset,
    mapping = aes(x = long, y = lat, group = group)
  ) + 
  coord_fixed(
    ratio = 1.3,
    xlim = c(-5, 130),
    ylim = c(30, 70)
  ) +
  plain +
  country.layer +
  geom_scatterpie(
    data = landmarks,
    aes(x = long, y = lat),
    cols = c("Hybrid", "Landrace", "Wild"),
    color = NA,
    pie_scale = 0.75
  ) +
  geom_point_svg(
    data = landmarks,
    aes(x = long, y = lat), svg = svg_txt, size = 5) + 
  labs(fill = "Domestication") +
  theme(
    legend.text = element_text(color = "black", size = 9, face = "bold"),
    legend.position = "bottom"
  )
ggsave("outputs/maps/map.pdf")
Fig1_map
```
