---
title: "Tax4Fun"
author: "Carolina Lobato"
date: "2024-02-22"
output: html_document
---

#Reference: <https://github.com/bwemheu/Tax4Fun2>

# Install package, reference data and dependencies

```{r}
#For buildDependencies, there was a probelm with installing blastn. 
#Details in Test Skript.
#Use use_force = T

# install.packages(pkgs = "scripts/utils/Tax4Fun2_1.1.5.tar.gz", 
#                  repos = NULL, 
#                  source = TRUE)
```

# Load Libraries

```{r, include = F}
library(phyloseq)
library(microbiome)
library(tidyverse)
library(ggplot2)
library(Tax4Fun2)
```

```{r}
buildReferenceData()

testReferenceData(path_to_reference_data = "outputs/Tax4Fun/Tax4Fun2_ReferenceData_v2")

buildDependencies(path_to_reference_data =
                    "./Tax4Fun2_ReferenceData_v2",
                  install_suggested_packages = T,
                  use_force = T)
```

#Create tables to use

```{r}
seq <- refseq(bh)

bh %>%
  refseq() %>%
  Biostrings::writeXStringSet("outputs/Tax4fun/seq.fna",
                              append = F,
                              compress = F,
                              compression_level = NA,
                              format = "fasta")
otu <- bh %>%
  otu_table() %>%
  as.matrix %>%
  data.frame
  
  write.table(otu,
              "outputs/Tax4fun/otu.txt",
              sep = "\t",
              row.names = T,
              quote = F)
```

# Making functional predictions

## Dna-sequences and otu table formatted as example data -\> easy

## Folder: path_to_temp_folder -\> made by me. All files created by RefBlast and MakeFunctPred are saved automatically in this folder

```{r}
# 1. Run the reference blast
runRefBlast(
  path_to_otus = "outputs/Tax4Fun/seq.fna",
  path_to_reference_data = "outputs/Tax4Fun/Tax4Fun2_ReferenceData_v2",
  path_to_temp_folder = "outputs/Tax4Fun/output_Ref99NR", #"Ref100NR"
  database_mode = "Ref99NR", #"Ref100NR"
  use_force = T,
  num_threads = 6)

# 2. Predicting functional profiles
makeFunctionalPrediction(
  path_to_otu_table = "outputs/Tax4fun/otu.txt",
  path_to_reference_data = "outputs/Tax4Fun/Tax4Fun2_ReferenceData_v2", 
  path_to_temp_folder = "outputs/Tax4Fun/output_Ref99NR", #"Ref100NR"
  database_mode = "Ref99NR", #"Ref100NR"
  normalize_by_copy_number = T,
  min_identity_to_reference = 0.97,
  normalize_pathways = F) #T
```

# Calculating functional redundancy indices

```{r}
# 1. Run the reference blast
# redundant, as it is the same blast as above
runRefBlast(
  path_to_otus = "outputs/Tax4Fun/seq.fna",
  path_to_reference_data = "outputs/Tax4Fun/Tax4Fun2_ReferenceData_v2",
  path_to_temp_folder = "outputs/Tax4Fun/output_Ref99NR",
  database_mode = "Ref99NR",
  use_force = T,
  num_threads = 6)

# 2. Calculating FRIs
calculateFunctionalRedundancy(
  path_to_otu_table = "outputs/Tax4fun/otu.txt",
  path_to_reference_data = "outputs/Tax4Fun/Tax4Fun2_ReferenceData_v2",
  path_to_temp_folder = "outputs/Tax4Fun/output_Ref99NR",
  database_mode = "Ref99NR",
  min_identity_to_reference = 0.97)
```

```{r}

```
