---
title: "Chapter 3.1: Diversity"
author: "Carolina Lobato"
date: "23/02/2023"
output: html_document
---

# Load Libraries

```{r, include = FALSE}
library(phyloseq)
library(stats)
library(ggpubr)
library(tidyverse)
library(ggplot2)
library(colorspace)
library(asremlPlus)
```

# Diversity Metrics

```{r, echo = FALSE}
load("outputs/r/204_setup/bh_raref.RData")
# load("outputs/r/204_setup/subsets/bh-chem-raref.RData") # bh_chem_raref
# load("outputs/r/204_setup/subsets/bh-dom-raref.RData") # bh_dom_raref
# load("outputs/r/204_setup/subsets/bh-flo-raref.RData") # bh_flo_raref
# load("outputs/r/204_setup/subsets/bh-mj-raref.RData") # bh_mj_raref

# bh_new <- subset_samples(bh_raref, provider == "IPK"); bh_new

richness <- phyloseq::estimate_richness(
  bh_dom_raref,
  measures = c("Shannon", "Observed"))
head(richness) # returns a data.frame
summary(richness)

alpha <- cbind(sample_data(bh_dom_raref), richness); alpha

# Check distribution
hist(richness$Shannon, main = "Shannon index", xlab = "") 
hist(richness$Observed, main = "Richness", xlab = "")

# Correlation between a given sample and the normal distribution.
ggpubr::ggqqplot(richness$Shannon) 
ggpubr::ggqqplot(richness$Observed) 

# Normality test: p < 0.05 implies a dist. sign. different from the normal dist. We can not assume normality.
shapiro.test(richness$Shannon) # p = 8.651e-10
shapiro.test(richness$Observed) # p = 8.341e-15

# parametric
# alpha_aov <- aov(Shannon ~ cultivar, alpha); alpha_aov  
# alpha_trk <- stats::TurkeyHSD(alpha_aov)

# non-parametric
alpha_kt_o <- kruskal.test(Observed ~ domestication, alpha); alpha_kt_o # p < 2.2e-16
alpha_kt_s <- kruskal.test(Shannon ~ domestication, alpha); alpha_kt_s # p < 2.2e-16
```

## Mean and Std. Error

```{r}
se <- function(x) {
  n <- length(x)
  sd(x)/sqrt(n)
}

alpha_stat <- alpha %>% 
  group_by(cultivar) %>% 
  dplyr::summarise_at(vars(Shannon, Observed),
                      list(mean = mean, 
                           se = se))

write.table(alpha_stat,
            "outputs/r/301_alpha_div/alpha-stat-cultivar.csv",
            sep = "\t",
            row.names = T,
            quote = FALSE)

summary(alpha)
sd(alpha$Observed)/sqrt(402) # 1.19
sd(alpha$Shannon)/sqrt(402) # 0.033
```

# Significance

## Heatmaps Prep

```{r}
# pairwise observed
alpha_wt_o <- pairwise.wilcox.test(
  alpha$Shannon,
  as.factor(alpha$domestication),
  p.adjust.method = "bonf"); alpha_wt_o 

alpha_wt_Obs <- as.data.frame(alpha_wt_o[["p.value"]])
alpha.wt.Obs.long <- rownames_to_column(alpha_wt_Obs, 
                                        var = "C1") %>% 
  pivot_longer(cols = everything() & !C1,
               names_to = "C2", 
               values_to = "p") %>%
  filter(!is.na(p))
summary(alpha.wt.Obs.long)

# pairwise shannon
alpha_wt_s <- pairwise.wilcox.test(
  alpha$Shannon,
  as.factor(alpha$cultivar),
  p.adjust.method = "bonf"); alpha_wt_s 

alpha_wt_Shannon <- as.data.frame(alpha_wt_s[["p.value"]])
alpha.wt.Shannon.long <- rownames_to_column(alpha_wt_Shannon, 
                                            var = "C1") %>% 
  pivot_longer(cols = everything() & !C1, 
               names_to = "C2", 
               values_to = "p") %>%
  filter(!is.na(p))
summary(alpha.wt.Shannon.long)

# save
save(alpha.wt.Obs.long, 
     file = "outputs/r/301_alpha_div/alpha-observed-long.RData")
save(alpha.wt.Shannon.long, 
     file = "outputs/r/301_alpha_div/alpha-shannon-long.RData")
```

### Heatmaps

```{r}
load("outputs/r/301_alpha_div/alpha-observed-long.RData") #alpha.wt.Obs.long
load("outputs/r/301_alpha_div/alpha-shannon-long.RData") #alpha.wt.Shannon.long

sig.Obs <- plotPvalues(alpha.wt.Obs.long, 
            p = "p",
            x = "C1",
            y = "C2", 
            gridspacing = 0, 
            show.sig = T,
            alpha = 0.05, 
            sig.size = 3,
            sig.colour = "black", 
            sig.face = "plain", 
            triangles = "both", 
            title = "", 
            axis.labels = NULL, 
            axis.text.size = 8, 
            colours = c("#FC8D62", "#8DA0CB"),
            ggplotFuncs = NULL, 
            printPlot = T)

# ggsave("outputs/visual/r/301_alpha_div/sig-obs-wt.png", 
#        bg = "white",
#        width = 20,
#        height = 18,
#        units = "cm",
#        dpi = 600)

sig.Shannon <- plotPvalues(alpha.wt.Shannon.long, 
            p = "p",
            x = "C1",
            y = "C2", 
            gridspacing = 0, 
            show.sig = T,
            alpha = 0.05, 
            sig.size = 3,
            sig.colour = "black", 
            sig.face = "plain", 
            triangles = "both", 
            title = "", 
            axis.labels = NULL, 
            axis.text.size = 8, 
            colours =  c("#FC8D62", "#8DA0CB"),
            ggplotFuncs = NULL, 
            printPlot = T)

# ggsave("outputs/visual/r/301_alpha_div/sig-shannon-wt.png", 
#        bg = "white",
#        width = 20,
#        height = 18,
#        units = "cm",
#        dpi = 600)
```

```{r}
cowplot::plot_grid(sig.Obs, sig.Shannon, labels = c('A', 'B'), label_size = 12)

ggsave("outputs/visual/r/301_alpha_div/sig-alpha-wt.png", 
       bg = "white",
       width = 40,
       height = 18,
       units = "cm",
       dpi = 600)
```

# Plot Alpha-diversity: Variety

```{r, echo = FALSE}
load("outputs/r/204_setup/bh_raref.RData")

#bh_new <- subset_samples(bh_raref, provider == "IPK"); bh_new

palette_name <- "Geyser"
mycolors <- divergingx_hcl(46, palette = palette_name, rev = F)

alpha_all <- phyloseq::plot_richness(
  bh_raref, 
  x = "cultivar", 
  scales = "free_y", 
  nrow = 2,
  measures = c("Shannon", "Observed"),
  sortby = "Observed") + 
  geom_boxplot(aes(fill = cultivar), 
               alpha = 1, 
               show.legend = F) +
  theme_bw() +
  theme(
    axis.text.x = (element_text(angle = 45,
                                hjust = 1)),
    legend.position = "right",
    legend.box = "vertical",
    legend.direction = "vertical",
    strip.background = element_blank(),
    strip.text = element_blank()) +
  scale_fill_manual(values = mycolors, 
                    aesthetics = "fill", 
                    na.translate = T) +
  labs(x = "", 
       fill = "Cultivar", 
       shape = "")
alpha_all
# ggsave("outputs/visual/r/301_alpha_div/alpha-div-variety.png",
#        width = 24,
#        height = 16,
#        units = "cm",
#        scale = 1,
#        dpi = 600)
```

# Plot Alpha-diversity: Chemotype

```{r, echo = FALSE}
load("outputs/r/204_setup/subsets/bh-chem-raref.RData") # bh_chem_raref

palette_name <- "Geyser"
mycolors <- divergingx_hcl(2, palette = palette_name, rev = F)

alpha_chem <- phyloseq::plot_richness(
  bh_chem_raref, 
  x = "chemotype", 
  scales = "free_y", 
  nrow = 2,
  measures = c("Shannon", "Observed"),
  sortby = "Observed") + 
  geom_boxplot(aes(fill = chemotype2), 
               alpha = 1, 
               show.legend = F) +
  theme_bw() +
  theme(
    axis.text.x = (element_text(angle = 45,
                                hjust = 1)),
    axis.title.y = (element_text(size = 9)),
    legend.position = "right",
    legend.box = "vertical",
    legend.direction = "vertical",
    strip.background = element_blank(),
    strip.text = element_blank()) +
  scale_fill_manual(values = mycolors, 
                    aesthetics = "fill", 
                    na.translate = T) +
  labs(x = "", 
       fill = "Cannabinoid \nlevel", 
       shape = "")

# ggsave("outputs/visual/r/301_alpha_div/alpha-div-chem2.png",
#        width = 24,
#        height = 16,
#        units = "cm",
#        scale = 1,
#        dpi = 600)
```

# Plot Alpha-diversity: Domestication

```{r, echo = FALSE}
load("outputs/r/204_setup/subsets/bh-dom-raref.RData") # bh_dom_raref

palette_name <- "Geyser"
mycolors <- divergingx_hcl(4, palette = palette_name, rev = F)

alpha_dom <- phyloseq::plot_richness(
  bh_dom_raref, 
  x = "domestication", 
  scales = "free_y", 
  nrow = 2,
  measures = c("Shannon", "Observed"),
  sortby = "Observed") + 
  geom_boxplot(aes(fill = domestication), 
               alpha = 1, 
               show.legend = F) +
  theme_bw() +
  theme(
    axis.text.x = (element_text(angle = 45,
                                hjust = 1)),
    axis.title.y = (element_text(size = 9)),
    legend.position = "right",
    legend.box = "vertical",
    legend.direction = "vertical",
    strip.background = element_blank(),
    strip.text = element_blank()) +
  scale_fill_manual(values = mycolors, 
                    aesthetics = "fill", 
                    na.translate = T) +
  labs(x = "", 
       fill = "Domestication stage", 
       shape = "")

# ggsave("outputs/visual/r/301_alpha_div/alpha-div-dom.png",
#        width = 24,
#        height = 16,
#        units = "cm",
#        scale = 1,
#        dpi = 600)
```

## Merge Alpha-diverisity plots

```{r}
chem_dom <- cowplot::plot_grid(alpha_chem, alpha_dom,
                   label_size = 12,
                   align = "h",
                   byrow = T,
                   rel_heights = c(1,1))

alpha_final <- cowplot::plot_grid(alpha_all, chem_dom,
                                label_size = 12,
                                align = "v",
                                nrow = 2,
                                rel_heights = c(2, 1))

ggsave("outputs/visual/r/301_alpha_div/alpha-div-final.png", 
       bg = "white",
       width = 40,
       height = 18,
       units = "cm",
       dpi = 600)
```
