---
title: "Chapter 3.2: Structure"
author: "Carolina Lobato"
date: "21/02/2023"
output: html_document
---

# Load Libraries

```{r, include = FALSE}
library(phyloseq)
library(metagMisc)
library(asremlPlus)
library(tidyverse)
library(vegan)
library(ggplot2)
library(ggrepel)
library(RColorBrewer)
```

# Distances

```{r, echo = FALSE}
load("outputs/r/204_setup/bh.RData")
# load("outputs/r/204_setup/subsets/bh-flo.RData") # bh_flo
# load("outputs/r/204_setup/subsets/bh-chem.RData") # bh_chem
# load("outputs/r/204_setup/subsets/bh-dom.RData") # bh_dom
# load("outputs/r/204_setup/subsets/bh-mj.RData") # bh_mj

#bh_new <- subset_samples(bh, provider == "CRI"); bh_new
#check <- unique(bh_new@sam_data[["replicates"]]);check

# correct uneven sequencing depth using cumulative sum scaling (CSS)
bh_css <- metagMisc::phyloseq_transform_css(bh, 
                                            norm = TRUE, 
                                            log = TRUE); bh_css

# get data
df_css <- data.frame(sample_data(bh_css)) 

# transpose the css ASV table as a matrix
dist_matrix_t <- t(data.frame(otu_table(bh_css)))

# generate a bray distance object
bh_css_bray <- vegan::vegdist(dist_matrix_t,
                              method = "bray")

# test significance
vegan::adonis2(bh_css_bray ~ cultivar,
               data = df_css)

# transpose if necessary to test pairwise significance
if (taxa_are_rows(bh_css)) {
    bh_css <- t(bh_css)
}

metadata <-
  as(sample_data(bh_css), "data.frame") %>%
  select(replicates, cultivar)

css_table <-
  as.data.frame(otu_table(bh_css)) %>%
  rownames_to_column("replicates")

df <-
  css_table %>%
  inner_join(metadata, by = "replicates") %>%
  select(cultivar, starts_with("ASV"))
  
# pairwise comparisons
pwadonis <-
  pairwiseAdonis::pairwise.adonis(
  df[, 2:5301],
  as.factor(df$cultivar),
  sim.function = "vegdist",
  sim.method = "bray",
  p.adjust.m = "fdr")

# coerce to data.frame and save
pwadonis_df = as.data.frame(pwadonis)
# write.csv(pwadonis_df, 
#           file = "outputs/r/302_beta_div/pw-adonis.csv")
```

# MDS

```{r, echo = FALSE}
# Non-metric MultiDimenstional Scaling
bh_MDS <- ordinate(bh_css, "MDS", "bray", trymax = 1000); bh_MDS

mycolors <- colorRampPalette(brewer.pal(5, "Paired"))(5)
column1 <- sample_data(bh_css)$domestication
column2 <- sample_data(bh_css)$chemotype
column3 <- sample_data(bh_css)$cultivar

plot_ordination(bh_css, bh_MDS) + 
  geom_point(
    aes(col = as.factor(column1), 
        shape = as.factor(column2)),
        size = 5,
    show.legend = T)+
  geom_text(aes(label = as.factor(column3)), 
            size = 2) +
#  scale_shape_manual(values = c(19, 18, 15, 17)) +
#  stat_ellipse(type = "norm", linetype = 1, level = 0.95) + 
  scale_color_manual(values = mycolors) +
  theme_classic() +
  theme(
    legend.position = "right",
    legend.box = "vertical",
    legend.direction = "vertical") +
  ggtitle("") +
  labs(color = "", 
       shape = "")

ggsave(
  "outputs/visual/r/302_beta_div/mds-bray-mj-dom-chem.png",
  width = 20,
  height = 18,
  units = "cm",
  scale = 1,
  dpi = 600)
```

# Significance

## Heatmaps Prep

```{r}
# pairwise adonis
pwadonis_wide <- pwadonis_df %>%  select(c(1, 7)) %>%
  separate_wider_delim(cols = pairs,
                       delim = " vs ",
                       names = c("C1", "C2"))

swap_columns <- function(row) {
  if (row['C1'] < row['C2']) {
    tmp <- row['C1']
    row['C1'] <- row['C2']
    row['C2'] <- tmp
  }
  return(row)
}

pwadonis_wide_new <- as.data.frame(t(apply(pwadonis_wide, 1, swap_columns)))
pwadonis_wide_new$p.adjusted <- as.numeric(pwadonis_wide_new$p.adjusted)

# save
write.csv(pwadonis_wide_new, 
          file = "outputs/r/302_beta_div/pw-adonis-wide-new.csv")
save(pwadonis_wide_new,
     file = "outputs/r/302_beta_div/pw-adonis-wide-new.RData")
```

### Heatmaps

```{r}
load("outputs/r/302_beta_div/pw-adonis-wide-new.RData") #pwadonis_wide_new

sig.pwa <- asremlPlus::plotPvalues(pwadonis_wide_new, 
            p = "p.adjusted",
            x = "C1",
            y = "C2", 
            gridspacing = 0, 
            show.sig = T,
            alpha = 0.05, 
            sig.size = 3,
            sig.colour = "black", 
            sig.face = "plain", 
            triangles = "lower", 
            title = "", 
            axis.labels = NULL, 
            axis.text.size = 8, 
            colours = c("#FC8D62", "#8DA0CB"),
            ggplotFuncs = NULL,
            sortFactor = "p.adjusted",
            printPlot = T)

ggsave("outputs/visual/r/302_beta_div/sig-pwa.png",
       bg = "white",
       width = 20,
       height = 18,
       units = "cm",
       dpi = 600)
```
