---
title: "Chapter 1: General Overview"
author: "Carolina Lobato"
date: "23/02/2023"
output: html_document
---

# Load Libraries

```{r include = FALSE}
library(phyloseq)
library(microbiome)
library(microbiomeutilities)
library(microViz)
library(metagMisc)
library(tidyverse)
library(ggplot2)
library(metacoder)
library(colorspace)
library(png)
```

# Dominant Taxa

```{r, echo = FALSE}
load("outputs/r/204_setup/bh.RData")

# dominant taxonomic group, n and percent sample that are dominated by each taxon
dom_sum <- microbiomeutilities::dominant_taxa(
  bh,
  level = "Class")
dom_sum$dominant_overview

# Relative abundances
genus_table <-
 bh %>%
 phyloseq::merge_samples(group = "cultivar", 
                         fun = mean) %>%
 phyloseq::transform_sample_counts(function(x) x / sum(x) * 100) %>%
  microbiome::aggregate_rare(level = "Genus", 
                             detection = 1, 
                             prevalence = 0, 
                             include.lowest = F) %>%
  psmelt() %>%
  select(Sample,
         Abundance, 
         Genus) %>%
  group_by(Genus, Sample) %>% 
  summarise(Abundance = mean(Abundance))

class_table <-
 bh %>%
 phyloseq::merge_samples(group = "cultivar", fun = mean) %>%
 phyloseq::transform_sample_counts(function(x) x / sum(x) * 100) %>%
 microbiome::aggregate_rare(level = "Class", 
                            detection = 1, 
                            prevalence = 0, 
                            include.lowest = F) %>%
 psmelt() %>%
 select(Sample, 
        Abundance, 
        Class) %>%
 group_by(Class, Sample) %>% 
  summarise(Abundance = mean(Abundance))

# ASV richness of the dominant classes, total = 65,5% (3473 ASV in 5300)
bh # 5300 taxa and 451 samples
cla_gmm <-  microViz::tax_select(bh, 
                                 tax_list = "Gammaproteobacteria", 
                                 ranks_searched = "Class", 
                                 strict_matches = T); cla_gmm # 1367 taxa (25,7%) 
cla_alp <-  microViz::tax_select(bh, 
                                 tax_list = "Alphaproteobacteria", 
                                 ranks_searched = "Class", 
                                 strict_matches = T); cla_alp # 796 taxa (15,01%)  
cla_bcl <-  microViz::tax_select(bh, 
                                 tax_list = "Bacilli", 
                                 ranks_searched = "Class",  
                                 strict_matches = T); cla_bcl # 672 taxa (12,6%) 
cla_act <-  microViz::tax_select(bh, 
                                 tax_list = "Actinobacteria", 
                                 ranks_searched = "Class", 
                                 strict_matches = T); cla_act # 638 taxa  (12,03%) 


gen_bacillus <-  microViz::tax_select(bh, 
                                 tax_list = "Bacillus", 
                                 ranks_searched = "Genus", 
                                 strict_matches = T); gen_bacillus # 256 taxa 

gen_ralstonia <-  microViz::tax_select(bh, 
                                 tax_list = "Ralstonia", 
                                 ranks_searched = "Genus",  
                                 strict_matches = T); gen_ralstonia # 137 taxa

gen_pantoea <-  microViz::tax_select(bh, 
                                 tax_list = "Pantoea", 
                                 ranks_searched = "Genus", 
                                 strict_matches = T); gen_pantoea # 54 taxa


bh_mer <- phyloseq::merge_samples(bh, group = "cultivar", fun = mean)

# dominant taxonomic group, n and percent sample that are dominated by each taxon
dom_sum <- microbiomeutilities::dominant_taxa(
  bh_mer,
  level = "Class")
dom_sum$dominant_overview

# retrieves the dominant taxonomic group of each sample
sample_dom <- dominant(
  bh_mer, 
  level = "Genus"); sample_dom

```

# Abundance-Occupancy

```{r, echo = FALSE}
load("outputs/r/204_setup/bh_raref.RData")

asv <- otu_table(bh_raref) 
taxo <- tax_table(bh_raref) 
meta <- meta(bh_raref) 

# presence-absence data
ASV_PA <- 1 * ((asv > 0) == 1)

# occupancy calculation
ASV_prev <- rowSums(ASV_PA) / ncol(ASV_PA)

# relative abundance
ASV_rel <- apply(vegan::decostand(asv, 
                                  method = "total", 
                                  MARGIN = 2), 1, mean)

# combine occupancy and RA of each ASV in a table
ASV_prev_rel <- rownames_to_column(as.data.frame(cbind(ASV_prev, ASV_rel)), "ASV")

ASV_prev_rel_taxo <- rownames_to_column(as.data.frame(taxo),
                                        "ASV") 
ASV_prev_rel_taxo <- merge(ASV_prev_rel_taxo, 
                           ASV_prev_rel, 
                           by = "ASV")

# merge with metadata
ASV1 <- rownames_to_column(as.data.frame(t(asv)),
                           "replicates")

ASV_use1 <- merge(meta, 
                  ASV1, 
                  by = "replicates")

# keep only the one feature column for collapsing table
ASV_use1_1 <- ASV_use1[-c(1:3, 5:20)]

ASV_cultivar <- ASV_use1_1 %>% 
  group_by(cultivar) %>% 
  summarise_each(list(sum))

# make a ASV P/A table
ASV_cultivar_PA <- 1 * ((ASV_cultivar > 0) == 1)

# merge prevalence, RA and taxa with the nº of observations
ASV_obs_cultivar <- data.frame(colSums(ASV_cultivar_PA)) %>%
  na.omit() %>% 
  rownames_to_column("ASV")
names(ASV_obs_cultivar)[names(ASV_obs_cultivar) == "colSums.ASV_cultivar_PA."] <- 'Obs'

ASV_prev_rel_taxo_obs_cultivar_raref <- merge(ASV_prev_rel_taxo, 
                                              ASV_obs_cultivar, 
                                              by = "ASV")

# save(ASV_prev_rel_taxo_obs_cultivar_raref,
# file = "outputs/r/303_bac_comp/prev-rel-taxo-obs-cultivar-raref.RData")
```

## Prep Scatter Plot

```{r, echo = FALSE}
load("outputs/r/303_bac_comp/prev-rel-taxo-obs-cultivar-raref.RData") # ASV_prev_rel_taxo_obs_cultivar_raref

ASV_prev_rel_taxo_obs_cultivar_sub <- 
  ASV_prev_rel_taxo_obs_cultivar_raref %>% 
  arrange(desc(ASV_rel)) %>%
  mutate(
    Most_abundant_class =
      Class %in% c("Gammaproteobacteria", 
                   "Actinobacteria",
                   "Bacilli",
                   "Alphaproteobacteria")
    ) %>%   
  subset(Most_abundant_class == "TRUE")

# Count ASV observed by number of varieties
ASV_prev_rel_taxo_obs_cultivar_sub1 <-
  ASV_prev_rel_taxo_obs_cultivar_raref %>%
  dplyr::count(Obs, sort = T) 
sum(ASV_prev_rel_taxo_obs_cultivar_sub1$n) # total ASVs = 2799

# Count ASV observed by class
ASV_prev_rel_taxo_obs_cultivar_sub2 <-
  ASV_prev_rel_taxo_obs_cultivar_raref %>%
  dplyr::count(Class) %>%
  mutate(Most_abundant_class = Class %in% c("Gammaproteobacteria",
                                            "Actinobacteria",
                                            "Bacilli",
                                            "Alphaproteobacteria")) %>%
  dplyr::filter(Most_abundant_class == "TRUE")
```

### Scatter Plot

```{r, echo = FALSE}
palette_name <- "Heat"
mycolors <- sequential_hcl(9, palette = palette_name, rev = T)

g1 <- ggplot(
  ASV_prev_rel_taxo_obs_cultivar_sub,
  aes(x = ASV_rel, 
      y = ASV_prev)) +
  geom_point(aes(color = Obs),
             alpha = 1,
             size = 2) +
  xlab("Log10(Mean ASV relative abundance)") +
  ylab("ASV prevalence (%)") +
  scale_x_log10(labels = scales::trans_format("log10", scales::math_format(10 ^.x))) +
  scale_y_log10(labels = scales::percent_format(accuracy = 1)) +
  facet_wrap(~ Class, ncol = 4) +
  geom_label(data = ASV_prev_rel_taxo_obs_cultivar_sub2, 
             aes(x = 0.000001,
                 y = 1,
                 label = n),
             size = 3) +
  theme_classic() +
  theme(
    axis.title = element_text(size = 10, face = "bold"), 
    axis.text = element_text(size = 9, face = "bold"),
    legend.text = element_text(size = 8, face = "bold"),
    legend.title = element_text(size = 10, face = "bold"),
    legend.position = "bottom",
    legend.box = "horizontal",
    legend.direction = "horizontal",
    strip.background = element_blank(),
    strip.text = element_text(face = "bold"),
    panel.background = element_rect(
      fill = "white", 
      colour = "black",
      size = 0.5, 
      linetype = "solid"),
    panel.grid.major.y = element_line(
      size = 0.5,
      linetype = "dashed",
      colour = "black")) +
  guides(color = guide_legend(title = "", 
                              nrow = 1)) +
  scale_colour_gradientn(colours = mycolors,
                         breaks = c(1, 5, 10, 15, 20, 30, 35, 40, 46))
g1

# ggsave(
#   "outputs/visual/r/303_bac_comp/occ-ab-curves.png",
#    width = 20,
#    height = 24,
#    units = "cm",
#    scale = 1,
#    dpi = 600)
```

# Barplot Setup

```{r, echo = FALSE}
load("outputs/r/204_setup/bh.RData")
# load("outputs/r/204_setup/subsets/bh-chem.RData") # bh_chem
# load("outputs/r/204_setup/subsets/bh-dom.RData") # bh_dom
# load("outputs/r/204_setup/subsets/bh-mj.RData") # bh_mj
# load("outputs/r/204_setup/subsets/bh-flo.RData") # bh_flo

bh_rel <- microbiome::transform(bh, "compositional")
bh_agr <- microbiome::aggregate_rare(
  bh_rel,
  level = "Genus",
  detection = 0.01,
  prevalence = 0,
  include.lowest = F); bh_agr # 41 taxa and 451 samples

# bh_ko <- phyloseq::subset_taxa(bh_agr, Genus != "Other"); bh_ko 
```

## Barplot Replicates

```{r, echo = FALSE}
palette_name <- "Paired"
mycolors <- divergingx_hcl(41, palette = palette_name, rev = F)

plot_bar(bh_agr, 
         x = "replicates", 
         fill = "Genus") +
    facet_wrap(~cultivar, 
               nrow = 4, 
               ncol = 12, 
               shrink = T, 
               scales = "free") +
    theme_classic() +
  scale_fill_manual(values = mycolors) +
  scale_y_continuous(expand = c(0, 0), 
                     label = scales::percent) +
  scale_x_discrete(expand = c(0, 0)) +
  theme(
    panel.grid.major.y = element_line(size = 14),
    axis.text.x = element_blank(),
    axis.text.y = element_text(size = 10),
    axis.title.y = element_blank(),
    legend.position = "bottom",
    legend.box = "vertical",
    legend.direction = "horizontal",
    legend.key.size = unit(0.5, 'cm'),
    legend.text = element_text(size = 12)) +
  labs(x = "", 
       y = "Relative abundance", 
       fill = "") +
  guides(fill = guide_legend(nrow = 3))

# ggsave("outputs/visual/r/303_bac_comp/genus-0.01-cultivar-grid.png",
#        width = 80,
#        height = 40,
#        units = "cm",
#        dpi = 600)
```

## Barplot of the most abundant Genus

```{r, echo = FALSE}
source("scripts/utils/plot_composition_v2.R")
load("outputs/r/204_setup/bh.RData")

bh_mer <- merge_samples(bh, "cultivar")
bh_rel <- microbiome::transform(bh_mer, "compositional")
bh_agr <- microbiome::aggregate_rare(
  bh_rel,
  level = "Genus",
  detection = 0.01,
  prevalence = 0,
  include.lowest = F); bh_agr # 24 taxa and 46 samples

tax_table(bh_agr)

sorting_asv <- ordered(
  bh_agr@tax_table@.Data[,"Genus"],
  levels = c("Burkholderia-Caballeronia-Paraburkholderia",
             "Enhydrobacter",
             "Enterobacter",
             "Kosakonia",
             "Pantoea",
             "Pelomonas",
             "Pseudomonas",
             "Ralstonia",
             # "Serratia",
             "Yersiniaceae",
             "Bacillus",
             "Brevibacillus",
             "Lysinibacillus",
             "Oenococcus",
             "Paenibacillus",
             # "Clavibacter",
             "Corynebacterium",
             "Curtobacterium",
             # "Microbacteriaceae",
             # "Micrococcaceae",
             "Micrococcus",
             "Pseudarthrobacter",
             "Rathayibacter",
             "Rhodococcus",
             "Methylobacterium-Methylorubrum",
             "Sphingomonas",
             "Chitinophagaceae",
             "Other"))

# "#F0E7BE", "#FAC291","#FBD3AE","#FCE3CB"
sorting_idx <- order(sorting_asv, decreasing = F, na.last = NA)
otu_order <- bh_agr@tax_table@.Data[sorting_idx, "Genus"]
color = c("#6A221D","#812F1F","#973C24","#A9502C","#C16C45",
          "#CB815D","#D49A75","#DDB48E","#E7CEA6",
          "#004953","#1F6469","#3D7B7F","#5B9295","#79A9AB",
          "#C9690A","#E07F28","#EB8A37","#F49546","#F7A156",
          "#F8B173","#3F7856","#7EC384","#524F81","#8D9091")

par(oma = c(12, 4, 4, 6) + 0.1)
plot_composition(
  bh_agr,
  sample.sort = "neatmap",
  otu.sort = otu_order,
  plot.type = "barplot") +
  geom_bar(stat = "identity",
           position = "stack") +
  scale_fill_manual(values = color) +
  scale_y_continuous(expand = c(0, 0), 
                     label = scales::percent) +
  scale_x_discrete(expand = c(0, 0)) +
  theme_classic() +
  theme(
    panel.grid.major.y = element_line(),
    axis.text.x = element_text(size = 12, 
                               angle = 45, 
                               hjust = 1),
    axis.text.y = element_text(size = 12),
    axis.title.y = element_text(size = 12),
    legend.position = "right",
    legend.box = "vertical",
    legend.direction = "vertical",
    legend.key.size = unit(0.8, 'cm'),
    legend.text = element_text(size = 12)) +
  labs(x = "", 
       y = "Relative abundance", 
       fill = "") +
  guides(fill = guide_legend(ncol = 1))

# ggsave("outputs/visual/r/303_bac_comp/genus-class-0.01.png",
#        width = 60,
#        height = 35,
#        units = "cm",
#        dpi = 600)
```

# Heat Tree

```{r, echo = FALSE}
load("outputs/r/204_setup/ps.RData")

ps_fil <- metagMisc::phyloseq_filter_taxa_rel_abund(ps, 
                                                    frac = 0.00001); ps_fil # 265 taxa with >1e-5 %RA

sample_data(ps_fil)$A <- "A"
p_mc <- metacoder::parse_phyloseq(ps_fil, 
                                  class_regex = "(.*)", 
                                  class_key = "taxon_name")
n_replicates <- length(sample_data(ps_fil)$replicates)

p_mc$data$read_props <- calc_obs_props(p_mc, 
                                       "otu_table",  
                                       groups = "A")
p_mc$data$read_abund <- calc_taxon_abund(p_mc, 
                                         data = "read_props")
print(p_mc)

to_plot <- p_mc %>%
  metacoder::filter_taxa(taxon_ranks == "Genus", 
                         supertaxa = TRUE, 
                         reassign_obs = F) %>%
  metacoder::filter_taxa(grepl(pattern = "^[a-zA-Z]+$", 
                               taxon_names), 
                         reassign_obs = F)

palette_name <- "Heat"
mycolors <- sequential_hcl(7, palette = palette_name, rev = T)

set.seed(1112)
h1 <- heat_tree(to_plot,
          node_label = taxon_names,
          node_size = as.integer((n_obs/181)*100),
          node_color = as.integer(to_plot$data$read_abund[['A']]*100,
                                  length = 0),
          node_color_range = mycolors,
#         edge_label = n_obs
          initial_layout = "reingold-tilford",
          layout = "davidson-harel",
          title = "",
          node_size_axis_label = "", #ASV count
          node_color_axis_label = "", #Rel. abundance (%)
          repel_labels = T)
h1

# ggsave("outputs/visual/r/303_bac_comp/heattree-relab-asv.png",
#        bg = "white",
#        width = 30,
#        height = 20,
#        units = "cm",
#        dpi = 600)
```

# Merge plots

```{r, out.width = "25%"}
ht <- grid::rasterGrob(png::readPNG("outputs/visual/r/303_bac_comp/heattree-relab-asv2.png"), 
                       interpolate = TRUE)
```

```{r}
cowplot::plot_grid(ht, g1, 
                   labels = c('A', 'B'), 
                   label_size = 12)

ggsave("outputs/visual/r/303_bac_comp/htg1.png", 
       bg = "white",
       width = 35,
       height = 20,
       units = "cm",
       dpi = 600)
```
