---
title: "Brevibacterium"
author: "Carolina Lobato"
date: "2023-10-05"
output: html_document
---

# Load Libraries

```{r include = FALSE}
library(phyloseq)
library(microbiome)
library(microbiomeutilities)
library(microViz)
library(metagMisc)
library(tidyverse)
library(ggplot2)
library(metacoder)
library(colorspace)
library(png)
```

```{r}
load("outputs/r/204_setup/bh.RData")
load("outputs/r/204_setup/bh_raref.RData")

genus_table_c <-
 bh_raref %>%
 phyloseq::merge_samples(group = "cultivar", 
                         fun = mean) %>%
 phyloseq::transform_sample_counts(function(x) x / sum(x) * 100) %>%
  microbiome::aggregate_rare(level = "Genus", 
                             detection = 0, 
                             prevalence = 0, 
                             include.lowest = F) %>%
  psmelt() %>%
  select(Sample,
         Abundance, 
         Genus) %>%
  group_by(Genus, Sample) %>% 
  summarise(Abundance = mean(Abundance))

brevibacterium_reads <-
  bh_raref %>%
  microbiome::aggregate_rare(level = "Genus", 
                             detection = 0, 
                             prevalence = 0, 
                             include.lowest = F) %>%
  psmelt() %>%
  select(Sample,
         Abundance, 
         Genus) %>%
  filter(Genus == "Brevibacterium") %>%
  filter(Abundance > 0) %>%
  summarise(Abundance = sum(Abundance)) # 347, 40 in rarefied data

total_reads <- sum(sample_sums(bh)) # 36,996,923 
total_reads_rf <- sum(sample_sums(bh_raref)) # 2,254,014 
brevibacterium_RA <- brevibacterium_reads * 100 / total_reads # 0.0009%
brevibacterium_RA_rf <- brevibacterium_reads * 100 / total_reads_rf # 0.0018%


gen_brevibacterium <-  microViz::tax_select(bh_raref, 
                                 tax_list = "Brevibacterium", 
                                 ranks_searched = "Genus", 
                                 strict_matches = T); gen_brevibacterium # 7 taxa, 5 in rarefied data

brevib_ASV_per <- 7 * 100 / 5300 # 0.13 of the ASV richness
brevib_ASV_per_rf <- 5 * 100 / 2802 # 0.178 of the ASV richness

taxa_sums(gen_brevibacterium) # 4393 Brevibacterium = 58 reads, 24 in rarefied data
brevib4393_RA <- 58 * 100 / total_reads # 0.000157%
brevib4393_RA_rf <- 24 * 100 / total_reads_rf # 0.001%
brevib4393_ASV_per <- 1 * 100 / 5300 # 0.019 of the ASV richness
```

# Prevalence and %RA of core and flexible taxa

```{r, echo = FALSE}
load("outputs/r/204_setup/bh.RData")

asv <- otu_table(bh) 
taxo <- tax_table(bh) 
meta <- microbiome::meta(bh) 

# presence-absence data
ASV_PA <- 1 * ((asv > 0) == 1)

# occupancy calculation
ASV_prev <- rowSums(ASV_PA) / ncol(ASV_PA)

# relative abundance
ASV_rel <- apply(vegan::decostand(asv, 
                                  method = "total", 
                                  MARGIN = 2), 1, mean)

# combine occupancy and RA of each ASV in a table
ASV_prev_rel <- rownames_to_column(as.data.frame(cbind(ASV_prev, ASV_rel)), "ASV")

ASV_prev_rel_taxo <- rownames_to_column(as.data.frame(taxo),
                                        "ASV") 
ASV_prev_rel_taxo <- merge(ASV_prev_rel_taxo, 
                           ASV_prev_rel, 
                           by = "ASV")

# merge with metadata
ASV1 <- rownames_to_column(as.data.frame(t(asv)),
                           "replicates")

ASV_use1 <- merge(meta, 
                  ASV1, 
                  by = "replicates")

# keep only the one feature column for collapsing table
ASV_use1_1 <- ASV_use1[-c(1:3, 5:17)]

ASV_cultivar <- ASV_use1_1 %>% 
  group_by(cultivar) %>% 
  summarise_each(list(sum)) %>% 
  filter(cultivar %in% "Hohenthurmer G. R.")

# make a ASV P/A table
ASV_cultivar_PA <- 1 * ((ASV_cultivar > 0) == 1)

# merge prevalence, RA and taxa with the nยบ of observations
ASV_obs_cultivar <- data.frame(colSums(ASV_cultivar_PA)) %>%
  na.omit() %>% 
  rownames_to_column("ASV")
names(ASV_obs_cultivar)[names(ASV_obs_cultivar) == "colSums.ASV_cultivar_PA."] <- 'Obs' 

ASV_prev_rel_taxo_obs_cultivar <- merge(ASV_prev_rel_taxo, 
                                        ASV_obs_cultivar, 
                                        by = "ASV") %>% 
  mutate(ASV_rel_p = ASV_rel * 100, ASV_prev_p = ASV_prev * 100) %>%
  filter(Obs > 0)
```

### Scatter Plot

```{r}
color_species = c(Brevibacterium = "#C7522B")

p_ab_prev <- 
  ggplot(
    ASV_prev_rel_taxo_obs_cultivar,
    aes(x = ASV_rel_p, 
        y = ASV_prev_p, 
        color = Obs,
        size = Species)) +
      geom_point(size = 3, 
                 alpha = 0.25) + 
  ggrepel::geom_text_repel(data = subset(ASV_prev_rel_taxo_obs_cultivar, 
                          Species == "Brevibacterium"),
                          aes(ASV_rel_p,
                              ASV_prev_p,
                              label = ASV),
                          size = 3,
                          show.legend = F,
                          max.overlaps = 20) +
  geom_hline(yintercept = 75,
             linetype = "dashed", 
             color = "black") +
  geom_vline(xintercept = 0.1, 
             linetype = "dashed", 
             color = "black") +
      theme_classic() +
      theme(
        axis.title = element_text(size = 10),
        axis.text = element_text(size = 10),
        legend.text = element_text(size = 10),
        legend.position = "right",
        legend.direction = "vertical",
        panel.spacing = unit(0.1, "lines")) +
      scale_x_log10(breaks = c(10, 0.1, 0.001), 
                    labels = c(10, 0.1, 0.001)) +
      scale_color_manual(values = color_species)	+
      labs(x = "Relative Abundance (%)", 
           y = "ASV Prevalence (%)", 
           color = "")
p_ab_prev

# ggsave("outputs/visual/r/307_brevibacterium/ab-prev-curve-MasterKush.png",
#         width = 20,
#         height = 18,
#         units = "cm",
#         scale = 1,
#         dpi = 600)
```
