---
title: "Differential abundance"
author: "Carolina Lobato"
date: "2023-11-10"
output: html_document
---

# Load Libraries

```{r, include = F}
library(phyloseq)
library(tidyverse)
library(ggplot2)
library(vegan)
library(pheatmap)
library(ComplexUpset)
library(microbiome)
# BiocManager::install('DESeq2')
library(DESeq2)
library(RColorBrewer)
```

# Plot Alpha-diversity: Domestication

```{r, echo = FALSE}
load("outputs/r/204_setup/bh_raref.RData") # bh_raref

bh_dom_raref <- subset_samples(bh_raref, !is.na(domestication))
bh_dom_raref <- prune_taxa(taxa_sums(bh_dom_raref) > 0, bh_dom_raref)

palette_name <- "Geyser"
mycolors <- divergingx_hcl(6, palette = palette_name, rev = F)

alpha_dom <- phyloseq::plot_richness(
  bh_dom_raref, 
  x = "domestication", 
  scales = "free_y", 
  nrow = 2,
  measures = c("Shannon", "Observed"),
  sortby = "Observed") + 
  geom_boxplot(aes(fill = domestication), 
               alpha = 1, 
               show.legend = F) +
  theme_bw() +
  theme(
    axis.text.x = (element_text(angle = 45,
                                hjust = 1)),
    axis.title.y = (element_text(size = 9)),
    legend.position = "right",
    legend.box = "vertical",
    legend.direction = "vertical",
    strip.background = element_blank(),
    strip.text = element_blank()) +
  scale_fill_manual(values = mycolors, 
                    aesthetics = "fill", 
                    na.translate = T) +
  labs(x = "", 
       fill = "Domestication stage", 
       shape = "")
alpha_dom

ggsave("outputs/visual/r/311_diff_ab/alpha-div-dom.png",
       width = 24,
       height = 16,
       units = "cm",
       scale = 1,
       dpi = 600)
```

## Barplot

```{r, echo = FALSE}
load("outputs/r/204_setup/bh.RData")
# load("outputs/r/204_setup/subsets/bh-chem.RData") # bh_chem
load("outputs/r/204_setup/subsets/bh-dom.RData") # bh_dom
# load("outputs/r/204_setup/subsets/bh-mj.RData") # bh_mj
# load("outputs/r/204_setup/subsets/bh-flo.RData") # bh_flo

meta <- meta(bh)

bh_mer <- phyloseq::merge_samples(bh, "cultivar")
bh_rel <- microbiome::transform(bh_mer, "compositional")
# bh_subset <- subset_samples(bh, domestication == "Cross hybrid S1")
bh_agr <- microbiome::aggregate_rare(
  bh_rel,
  level = "best_hit",
  detection = 0.01,
  prevalence = 0,
  include.lowest = F); bh_agr

bh_ko <- phyloseq::subset_taxa(bh_agr, 
                               best_hit != "Other"); bh_ko 

otu <- data.frame(otu_table(bh_ko)) %>% rownames_to_column("ASV")
otu$ASV <- sub(": [a-z0-9]*:[a-z_]{0,3}", ": ", otu$ASV)
otu_fil <- otu %>% filter(otu$ASV %in% rownames(data)) %>% column_to_rownames("ASV")

otu_fil_t_land <- t(otu_fil) %>% data.frame() %>% rownames_to_column("ASV") %>%
  mutate(dom = "Landrace")
otu_fil_t_ibr <- t(otu_fil) %>% data.frame() %>% rownames_to_column("ASV") %>%
  mutate(dom = "Inbred_Line")
otu_fil_t_seg <- t(otu_fil) %>% data.frame() %>% rownames_to_column("ASV") %>%
  mutate(dom = "Segregating_Hybrid")
otu_fil_t_cxh <- t(otu_fil) %>% data.frame() %>% rownames_to_column("ASV") %>%
  mutate(dom = "Cross_Hybrid")
otu_fil_t_sel <- t(otu_fil) %>% data.frame() %>% rownames_to_column("ASV") %>%
  mutate(dom = "Selection")
otu_fil_t_cxs1 <- t(otu_fil) %>% data.frame() %>% rownames_to_column("ASV") %>%
  mutate(dom = "Cross_S1")

otu_fil_t_all <- full_join(otu_fil_t_land, otu_fil_t_cxs1)
otu_fil_t_all2 <- full_join(otu_fil_t_all, otu_fil_t_ibr)
otu_fil_t_all3 <- full_join(otu_fil_t_all2, otu_fil_t_seg)
otu_fil_t_all4 <- full_join(otu_fil_t_all3, otu_fil_t_cxh)
otu_fil_t_all5 <- full_join(otu_fil_t_all4, otu_fil_t_sel)

otu_fil_t_all5[is.na(otu_fil_t_all5)] <- "0"

write.table(otu_fil_t_all5,
            "outputs/r/311_dif_ab/ab_domc50_rep_all.csv",
            sep = ";",
            row.names = T,
            quote = FALSE)

otu <- data.frame(otu_table(bh_agr))
 
palette_name <- "Geyser"
mycolors <- colorRampPalette(brewer.pal(24, "Paired"))(24)

par(oma = c(12, 4, 6, 6) + 0.1)
plot_composition(
  bh_agr,
  # sample.sort = c("Landrace", "Selection", "Cross hybrid", "Inbred line"),
  # otu.sort = otu_order,
  plot.type = "barplot") +
  geom_bar(stat = "identity",
           position = "stack") +
  scale_fill_manual(values = mycolors) +
  scale_y_continuous(expand = c(0, 0), 
                     label = scales::percent) +
  scale_x_discrete(expand = c(0, 0)) +
  theme_classic() +
  theme(
    panel.grid.major.y = element_line(),
    axis.text.x = element_text(size = 16, 
                               angle = 45, 
                               hjust = 1),
    axis.text.y = element_text(size = 16),
    axis.title.y = element_text(size = 16),
    legend.position = "right",
    legend.box = "vertical",
    legend.direction = "vertical",
    legend.key.size = unit(1, 'cm'),
    legend.title = element_text(size = 16),
    legend.text = element_text(size = 16)) +
  labs(x = "", 
       y = "Relative abundance (%)", 
       fill = "Genus") +
  guides(fill = guide_legend(ncol = 1))

ggsave("outputs/visual/r/311_diff_ab/spe-0.01-dom-all.png",
       width = 80,
       height = 60,
       units = "cm",
       dpi = 600)
```

```{r}
load("outputs/r/204_setup/bh.RData")

meta <- meta(bh)

# pairwise comparison between gut and tongue
bh.sub <- subset_samples(bh, 
                         domestication %in% c("Selection", "Inbred line"))

# filter sparse features, with > 90% zeros
bh.sub.p <- prune_taxa(rowSums(otu_table(bh.sub) == 0) < ncol(otu_table(bh.sub)) * 0.9,
                       bh.sub)

bh_ds <- phyloseq_to_deseq2(bh.sub.p, ~ domestication)

# use alternative estimator on a condition of "every gene contains a sample with a zero"
ds <- estimateSizeFactors(bh_ds, type = "poscounts")
ds <- DESeq(ds, test = "Wald", fitType = "parametric")
alpha <- 0.05 

res = results(ds, alpha = alpha)
res = res[order(res$padj, na.last = NA), ]
taxa_sig = rownames(res[1:20, ]) # select bottom 20 with lowest p.adj values
bh.rel <- transform_sample_counts(bh, function(x) x/sum(x)*100)
bh.rel.sig <- prune_taxa(taxa_sig, bh.rel)
# Only keep gut and tongue samples
bh.rel.sig <- prune_samples(colnames(otu_table(bh.sub.p)), bh.rel.sig)
```

```{r}
matrix <- as.matrix(data.frame(otu_table(bh.rel.sig)))

rownames(matrix) <- as.character(tax_table(bh.rel.sig)[, "best_hit"])

meta_sub <- data.frame(sample_data(bh.rel.sig))

# Define the annotation color for columns and rows
annotation_col <- data.frame(
  Subject = as.factor(meta_sub$cultivar), 
  Dom = as.factor(meta_sub$domestication), 
  check.names = F)
rownames(annotation_col) = rownames(meta_sub)

annotation_row <- data.frame(
  Phylum = as.factor(tax_table(bh.rel.sig)[, "best_hit"]))
rownames(annotation_row) = rownames(matrix)

# ann_color should be named vectors
phylum_col <- RColorBrewer::brewer.pal(length(levels(annotation_row$best_hit)), "Paired")
names(phylum_col) <- levels(annotation_row$best_hit)
ann_colors <- list(
    Subject = c("Fedora 17" = "red", "Havellander" = "blue", "Schurig" = "green",
                "Lovrin 110" = "orange", "Beniko" = "lightblue", "Ferimon" = "lightgreen", 
                "Felina 32" = "orchid", "Futura 75" = "pink", "Master Kush" = "forestgreen"),
    Dom = c(landrace = "purple", selection = "yellow"),
    Phylum = phylum_col)

ComplexHeatmap::pheatmap(matrix, 
                         scale = "row", 
                         annotation_col = annotation_col, 
                         annotation_row = annotation_row, 
                         annotation_colors = ann_colors)
```
